on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ‘14’

    - name: Install dependencies
      run: npm install

    - name: Build and test
      run: npm test

    - name: Deploy to GitHub Pages
      if: success()
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        npm run deploy
        
        